#ifndef PICKY_CONFIG_H
#define PICKY_CONFIG_H

#define PICKY_DEFAULT_WIDTH 800
#define PICKY_DEFAULT_HEIGHT 600

#define PICKY_WINDOW_TITLE "picky"
#define PICKY_APP_ID "picky"

#define PICKY_REGION_SIZE 75
#define PICKY_BORDER_SIZE 4

#define PICKY_INITIAL_HUE 0
#define PICKY_DEFAULT_FORMAT OUTFORMAT_HEX

#endif /* PICKY_CONFIG_H */
